import {
  Doctor,
  BonoItem,
  Liquidacion,
  PendingFund,
  DebtorAlert,
  DebitItem,
  AuthorizationItem,
  CajaRecord,
  ApiConnection,
  MessagingRule,
  TaskItem,
  AutomationLog,
} from '../types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Martín E. Ferreira',
    matricula: '45678',
    matriculaProvincial: 'MP-89211',
    specialty: 'Cardiología Intervencionista',
    circuloMedico: 'Círculo Médico Centro',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=256',
    email: 'mferreira@clinica.com',
    phone: '+54 11 4455-6677',
    docStatus: 'PENDIENTE',
    placesOfCare: ['Sanatorio San Lucas - Consultorio 4', 'Clínica del Sol - Piso 2'],
    conventions: ['OSDE (Plan 210/310/410)', 'Swiss Medical (SMG20/30)', 'Galeno Plata/Oro', 'IOMA'],
    documentation: {
      matriculaNacionalFile: 'matricula_nacional_2023.pdf',
      matriculaNacionalUpdate: '12/05/2023',
      matriculaNacionalStatus: 'Vigente',
      matriculaProvincialFile: undefined,
      matriculaProvincialStatus: 'No cargada',
      seguroMalaPraxisFile: 'poliza_seguro_2022.pdf',
      seguroMalaPraxisExpiry: '15/11/2023',
      seguroMalaPraxisStatus: 'Alerta',
    },
    automations: {
      emailAvisoVencimiento: true,
      envioResumenContador: false,
    },
  },
  {
    id: 'doc-2',
    name: 'Dr. Carlos Mendoza',
    matricula: 'MP-12456',
    matriculaProvincial: 'MN-90112',
    specialty: 'Cardiología',
    circuloMedico: 'Círculo Médico Centro',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=256',
    email: 'cmendoza@cardio.com',
    phone: '+54 11 4488-9900',
    docStatus: 'COMPLETO',
    placesOfCare: ['Centro Cardiovascular', 'Hospital Privado'],
    conventions: ['OSDE', 'Swiss Medical', 'Medifé'],
    documentation: {
      matriculaNacionalFile: 'mendoza_mat_nac.pdf',
      matriculaNacionalUpdate: '01/03/2023',
      matriculaNacionalStatus: 'Vigente',
      matriculaProvincialFile: 'mendoza_mat_prov.pdf',
      matriculaProvincialStatus: 'Vigente',
      seguroMalaPraxisFile: 'seguro_prudential_2024.pdf',
      seguroMalaPraxisExpiry: '28/02/2025',
      seguroMalaPraxisStatus: 'Vigente',
    },
    automations: {
      emailAvisoVencimiento: true,
      envioResumenContador: true,
    },
  },
  {
    id: 'doc-3',
    name: 'Dra. Ana Silva',
    matricula: 'MP-09823',
    matriculaProvincial: '',
    specialty: 'Pediatría',
    circuloMedico: 'Asociación Médica Norte',
    avatar: 'https://images.unsplash.com/photo-1594824813589-3543d2c88f9a?auto=format&fit=crop&q=80&w=256',
    email: 'anasilva.pediatria@gmail.com',
    phone: '+54 11 5566-7788',
    docStatus: 'PENDIENTE',
    placesOfCare: ['Consultorios Pediátricos del Norte'],
    conventions: ['OSDE', 'Galeno', 'IOMA', 'Sancor Salud'],
    documentation: {
      matriculaNacionalFile: 'silva_titulo_mat.pdf',
      matriculaNacionalUpdate: '10/08/2023',
      matriculaNacionalStatus: 'Vigente',
      matriculaProvincialFile: undefined,
      matriculaProvincialStatus: 'No cargada',
      seguroMalaPraxisFile: 'seguro_nobis_2023.pdf',
      seguroMalaPraxisExpiry: '30/10/2023',
      seguroMalaPraxisStatus: 'Alerta',
    },
    automations: {
      emailAvisoVencimiento: true,
      envioResumenContador: false,
    },
  },
  {
    id: 'doc-4',
    name: 'Dr. Luis Ramírez',
    matricula: 'MP-33412',
    matriculaProvincial: 'MN-77441',
    specialty: 'Traumatología',
    circuloMedico: 'Círculo Médico Sur',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=256',
    email: 'lramirez.trauma@clinica.ar',
    phone: '+54 11 4789-1234',
    docStatus: 'COMPLETO',
    placesOfCare: ['Instituto de Ortopedia y Traumatología', 'Clínica Quilmes'],
    conventions: ['OSDE', 'Swiss Medical', 'Omint', 'Federada Salud'],
    documentation: {
      matriculaNacionalFile: 'ramirez_mat_nacional.pdf',
      matriculaNacionalUpdate: '15/01/2023',
      matriculaNacionalStatus: 'Vigente',
      matriculaProvincialFile: 'ramirez_mat_prov.pdf',
      matriculaProvincialStatus: 'Vigente',
      seguroMalaPraxisFile: 'seguro_san_cristobal_2024.pdf',
      seguroMalaPraxisExpiry: '12/12/2024',
      seguroMalaPraxisStatus: 'Vigente',
    },
    automations: {
      emailAvisoVencimiento: true,
      envioResumenContador: true,
    },
  },
  {
    id: 'doc-5',
    name: 'Dra. Valeria Gómez',
    matricula: 'MP-77219',
    matriculaProvincial: 'MN-88992',
    specialty: 'Dermatología',
    circuloMedico: 'Colegio Médico Central',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=256',
    email: 'vgomez.derma@gmail.com',
    phone: '+54 11 4990-2211',
    docStatus: 'REVISIÓN',
    placesOfCare: ['Centro Dermatológico Integral'],
    conventions: ['OSDE', 'Swiss Medical', 'Galeno'],
    documentation: {
      matriculaNacionalFile: 'gomez_mat.pdf',
      matriculaNacionalUpdate: '20/09/2023',
      matriculaNacionalStatus: 'Vigente',
      matriculaProvincialFile: 'gomez_prov_borrador.pdf',
      matriculaProvincialStatus: 'Pendiente',
      seguroMalaPraxisFile: 'poliza_vencida.pdf',
      seguroMalaPraxisExpiry: '01/10/2023',
      seguroMalaPraxisStatus: 'Alerta',
    },
    automations: {
      emailAvisoVencimiento: true,
      envioResumenContador: false,
    },
  },
  {
    id: 'doc-6',
    name: 'Dr. Juan Pérez',
    matricula: 'MP-112233',
    matriculaProvincial: 'MN-44556',
    specialty: 'Cardiología',
    circuloMedico: 'Círculo Médico Centro',
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=256',
    email: 'jperez@medicos.com',
    phone: '+54 11 6677-8899',
    docStatus: 'COMPLETO',
    placesOfCare: ['Instituto Cardiovascular'],
    conventions: ['OSDE', 'Swiss Medical', 'PAMI'],
    documentation: {
      matriculaNacionalFile: 'perez_mat.pdf',
      matriculaNacionalUpdate: '04/04/2023',
      matriculaNacionalStatus: 'Vigente',
      matriculaProvincialFile: 'perez_prov.pdf',
      matriculaProvincialStatus: 'Vigente',
      seguroMalaPraxisFile: 'seguro_la_segunda.pdf',
      seguroMalaPraxisExpiry: '15/06/2025',
      seguroMalaPraxisStatus: 'Vigente',
    },
    automations: {
      emailAvisoVencimiento: true,
      envioResumenContador: true,
    },
  },
];

export const INITIAL_BONOS: BonoItem[] = [
  {
    id: 'bono-1',
    patientName: 'Perez, Maria',
    obraSocial: 'OSDE',
    date: '2023-10-12',
    practiceCode: '42.01.01',
    diagnosis: 'I10 - Hipertensión esencial',
    monto: 15000.0,
    copago: false,
    doctorName: 'Dr. Carlos Mendoza',
  },
  {
    id: 'bono-2',
    patientName: 'Gomez, Carlos',
    obraSocial: 'Swiss Medical',
    date: '2023-10-12',
    practiceCode: '42.01.05',
    diagnosis: 'E11 - Diabetes mellitus tipo 2',
    monto: 22500.0,
    copago: true,
    doctorName: 'Dra. Ana Silva',
  },
  {
    id: 'bono-3',
    patientName: 'Lopez, Ana',
    obraSocial: 'Galeno',
    date: '2023-10-13',
    practiceCode: '34.02.11',
    diagnosis: 'J00 - Rinofaringitis aguda',
    monto: 8200.0,
    copago: false,
    doctorName: 'Dr. Luis Ramírez',
  },
  {
    id: 'bono-4',
    patientName: 'Romero, Estela',
    obraSocial: 'OSDE',
    date: '2023-10-14',
    practiceCode: '42.01.01',
    diagnosis: 'M54.5 - Lumbago no especificado',
    monto: 18000.0,
    copago: false,
    doctorName: 'Dr. Juan Pérez',
  },
];

export const INITIAL_LIQUIDACIONES: Liquidacion[] = [
  {
    id: 'liq-oct-2023-osde',
    period: '2023-10',
    obraSocial: 'OSDE - Organización de Servicios Directos Empresarios',
    modalidad: 'agrupada',
    practicasCount: 1452,
    montoTotal: 4500000.0,
    doctorsCount: 45,
    status: 'PROCESADA',
    doctorDetails: [
      {
        id: 'ld-1',
        doctorName: 'Dr. Pérez, Juan',
        specialty: 'Cardiología',
        cantPracticas: 145,
        monto: 450000.0,
        status: 'VERIFICADOS',
      },
      {
        id: 'ld-2',
        doctorName: 'Dra. Gómez, María',
        specialty: 'Pediatría',
        cantPracticas: 320,
        monto: 850200.0,
        status: 'VERIFICADOS',
      },
      {
        id: 'ld-3',
        doctorName: 'Dr. Rodríguez, Carlos',
        specialty: 'Traumatología',
        cantPracticas: 85,
        monto: 620000.0,
        status: 'REVISIÓN',
      },
      {
        id: 'ld-4',
        doctorName: 'Dra. Fernández, Laura',
        specialty: 'Dermatología',
        cantPracticas: 112,
        monto: 310500.0,
        status: 'VERIFICADOS',
      },
      {
        id: 'ld-5',
        doctorName: 'Dr. Benítez, Gonzalo',
        specialty: 'Ginecología',
        cantPracticas: 190,
        monto: 715000.0,
        status: 'VERIFICADOS',
      },
    ],
  },
  {
    id: 'liq-oct-2023-smg',
    period: '2023-10',
    obraSocial: 'Swiss Medical Group',
    modalidad: 'directa',
    practicasCount: 920,
    montoTotal: 3100000.0,
    doctorsCount: 32,
    status: 'EN_REVISION',
    doctorDetails: [
      {
        id: 'ld-6',
        doctorName: 'Dra. Silva, Ana',
        specialty: 'Pediatría',
        cantPracticas: 210,
        monto: 620000.0,
        status: 'VERIFICADOS',
      },
      {
        id: 'ld-7',
        doctorName: 'Dr. Ramírez, Luis',
        specialty: 'Traumatología',
        cantPracticas: 140,
        monto: 890000.0,
        status: 'VERIFICADOS',
      },
    ],
  },
];

export const INITIAL_PENDING_FUNDS: PendingFund[] = [
  {
    id: 'pf-1',
    liqId: 'LIQ-24-089',
    obraSocial: 'OSDE',
    period: 'Marzo 2024',
    montoTotal: 450000.0,
    status: 'Pendiente',
    selected: false,
  },
  {
    id: 'pf-2',
    liqId: 'LIQ-24-090',
    obraSocial: 'OSDE',
    period: 'Abril 2024',
    montoTotal: 850000.0,
    status: 'Pendiente',
    selected: true,
  },
  {
    id: 'pf-3',
    liqId: 'LIQ-24-092',
    obraSocial: 'Swiss Medical',
    period: 'Abril 2024',
    montoTotal: 120500.0,
    status: 'Pendiente',
    selected: false,
  },
  {
    id: 'pf-4',
    liqId: 'LIQ-24-085',
    obraSocial: 'OSDE',
    period: 'Febrero 2024',
    montoTotal: 150000.0,
    status: 'Parcial',
    selected: true,
  },
  {
    id: 'pf-5',
    liqId: 'LIQ-24-101',
    obraSocial: 'Galeno',
    period: 'Mayo 2024',
    montoTotal: 320000.0,
    status: 'Pendiente',
    selected: false,
  },
];

export const INITIAL_DEBTOR_ALERTS: DebtorAlert[] = [
  {
    id: 'deb-1',
    obraSocial: 'IOMA',
    period: 'Enero 2024',
    amount: 2150000.0,
    overdueDays: 45,
    contactEmail: 'prestadores@ioma.gba.gov.ar',
  },
  {
    id: 'deb-2',
    obraSocial: 'SANCOR SALUD',
    period: 'Febrero 2024',
    amount: 840000.0,
    overdueDays: 30,
    contactEmail: 'facturacion.medica@sancorsalud.com.ar',
  },
  {
    id: 'deb-3',
    obraSocial: 'PAMI UGL VIII',
    period: 'Diciembre 2023',
    amount: 1420000.0,
    overdueDays: 60,
    contactEmail: 'auditoria@pami.org.ar',
  },
];

export const INITIAL_DEBITS: DebitItem[] = [
  {
    id: 'deb-item-1',
    patientName: 'Rodríguez, María Teresa',
    patientId: '#88492',
    obraSocial: 'OSDE 310',
    invoiceNumber: 'FC-A-0023-000412',
    rejectionReason: 'Falta Historia Clínica',
    practice: '42.01.01 - Consulta Especialista',
    serviceDate: '12/10/2023',
    doctorName: 'Dr. Pérez, Juan',
    doctorMatricula: '112233',
    amount: 12500.0,
    status: 'Pendiente',
    attachedFile: undefined,
    auditNotes: 'La auditoría de OSDE requiere la historia clínica firmada y sello médico para validar la consulta de especialista.',
  },
  {
    id: 'deb-item-2',
    patientName: 'Gómez, Carlos Alberto',
    patientId: '#99210',
    obraSocial: 'Swiss Medical',
    invoiceNumber: 'FC-A-0023-000455',
    rejectionReason: 'Tope Excedido',
    practice: '42.01.05 - Consulta de Urgencia en Guardia',
    serviceDate: '08/10/2023',
    doctorName: 'Dra. Silva, Ana',
    doctorMatricula: '09823',
    amount: 18900.0,
    status: 'Pendiente',
    attachedFile: 'justificativo_tope_urgencia.pdf',
    auditNotes: 'Se superó el límite de 3 consultas mensuales del plan sin autorización previa de auditoría central.',
  },
  {
    id: 'deb-item-3',
    patientName: 'Vázquez, Lucía',
    patientId: '#44123',
    obraSocial: 'Galeno',
    invoiceNumber: 'FC-A-0023-000512',
    rejectionReason: 'Código Inexistente',
    practice: '34.02.11 - Ecografía Doppler Tisular',
    serviceDate: '15/10/2023',
    doctorName: 'Dr. Carlos Mendoza',
    doctorMatricula: '12456',
    amount: 28400.0,
    status: 'Pendiente',
    attachedFile: undefined,
    auditNotes: 'El código facturado no coincide con el nomenclador vigente acordado con Galeno para el plan Plata.',
  },
];

export const INITIAL_AUTHORIZATIONS: AuthorizationItem[] = [
  {
    id: 'aut-1',
    code: 'AUT-2938',
    patientName: 'Gomez, Roberto',
    doctorName: 'Dr. Martinez',
    obraSocial: 'OSDE',
    timeAgo: 'Hace 2h',
    status: 'pendientes',
    isAutomation: false,
    observation: 'Esperando validación de credencial digital del afiliado.',
  },
  {
    id: 'aut-2',
    code: 'AUT-2940',
    patientName: 'Fernandez, Maria',
    doctorName: 'Dra. Silva',
    obraSocial: 'Swiss Medical',
    timeAgo: 'Procesando...',
    status: 'tramite',
    isAutomation: true,
    progress: 68,
    observation: 'Validando token de seguridad vía API Swiss Medical...',
  },
  {
    id: 'aut-3',
    code: 'AUT-2935',
    patientName: 'Lopez, Carlos',
    doctorName: 'Dr. Perez',
    obraSocial: 'Galeno',
    timeAgo: 'Hace 4h',
    status: 'observadas',
    isAutomation: false,
    observation: 'Falta historia clínica adjunta.',
  },
  {
    id: 'aut-4',
    code: 'AUT-2920',
    patientName: 'Ruiz, Ana',
    doctorName: 'Dr. Mendoza',
    obraSocial: 'OSDE',
    timeAgo: 'Hace 1d',
    status: 'aprobadas',
    isAutomation: true,
    observation: 'Autorización N° 994812 aprobada sin coseguro.',
  },
  {
    id: 'aut-5',
    code: 'AUT-2945',
    patientName: 'Benítez, Horacio',
    doctorName: 'Dr. Ramírez',
    obraSocial: 'IOMA',
    timeAgo: 'Hace 30 min',
    status: 'tramite',
    isAutomation: true,
    progress: 42,
    observation: 'Sincronizando con padrón web IOMA...',
  },
];

export const INITIAL_CAJA_RECORDS: CajaRecord[] = [
  {
    id: 'caja-1',
    matricula: 'MP-12456',
    doctorName: 'Dr. Juan Pérez',
    specialty: 'Cardiología',
    grossBilling: 850000.0,
    retentionPercent: 5,
    retentionAmount: 42500.0,
    netPayable: 807500.0,
    status: 'Procesado',
  },
  {
    id: 'caja-2',
    matricula: 'MP-09823',
    doctorName: 'Dra. María Gómez',
    specialty: 'Pediatría',
    grossBilling: 620500.0,
    retentionPercent: 5,
    retentionAmount: 31025.0,
    netPayable: 589475.0,
    status: 'Procesado',
  },
  {
    id: 'caja-3',
    matricula: 'MP-33412',
    doctorName: 'Dr. Carlos López',
    specialty: 'Traumatología',
    grossBilling: 1250000.0,
    retentionPercent: 5,
    retentionAmount: 62500.0,
    netPayable: 1187500.0,
    status: 'Procesado',
  },
  {
    id: 'caja-4',
    matricula: 'MP-77219',
    doctorName: 'Dra. Ana Martínez',
    specialty: 'Dermatología',
    grossBilling: 480000.0,
    retentionPercent: 5,
    retentionAmount: 24000.0,
    netPayable: 456000.0,
    status: 'Pendiente',
  },
  {
    id: 'caja-5',
    matricula: 'MP-55102',
    doctorName: 'Dr. Luis Fernández',
    specialty: 'Ginecología',
    grossBilling: 915000.0,
    retentionPercent: 5,
    retentionAmount: 45750.0,
    netPayable: 869250.0,
    status: 'Procesado',
  },
];

export const INITIAL_API_CONNECTIONS: ApiConnection[] = [
  {
    id: 'api-1',
    code: 'OSDE',
    name: 'OSDE Portal API',
    lastSync: 'hace 5 min',
    status: 'Conectado',
    endpointUrl: 'https://api.osde.com.ar/v2/prestadores/auth',
    apiKeyMasked: 'osde_live_••••••••9482',
  },
  {
    id: 'api-2',
    code: 'SMG',
    name: 'Swiss Medical Group',
    lastSync: 'hace 1 hora',
    status: 'Conectado',
    endpointUrl: 'https://gateway.swissmedical.com/liquidaciones/sync',
    apiKeyMasked: 'smg_prod_••••••••3311',
  },
  {
    id: 'api-3',
    code: 'GAL',
    name: 'Galeno Portal',
    lastSync: 'Error de autenticación',
    status: 'Desconectado',
    endpointUrl: 'https://servicios.galeno.com.ar/ws/bonos',
    apiKeyMasked: 'gal_api_••••••••0041',
  },
];

export const INITIAL_MESSAGING_RULES: MessagingRule[] = [
  {
    id: 'rule-1',
    title: 'Resumen Mensual a Médicos',
    description: 'Enviar resumen de liquidación el día 5 de cada mes a todos los médicos activos.',
    enabled: true,
    schedule: 'Día 5 de cada mes a las 09:00',
    template: 'Estimado/a {DOCTOR_NAME}, adjuntamos el detalle de su liquidación correspondiente al período {PERIODO}. Total neto: {MONTO_NETO}.',
  },
  {
    id: 'rule-2',
    title: 'Aviso de Débitos a Clínicas',
    description: 'Notificar automáticamente a la clínica correspondiente cuando se registra un nuevo débito.',
    enabled: false,
    schedule: 'En tiempo real al registrar débito',
    template: 'Aviso: Se ha generado un débito de {OBRA_SOCIAL} para el paciente {PACIENTE} por motivo: {MOTIVO}.',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Presentar liquidación mensual OSDE (Octubre)',
    description: 'Cerrar lote de 145 prácticas y enviar facturación electrónica antes del vencimiento.',
    category: 'Liquidaciones',
    priority: 'Alta',
    dueDate: '2023-10-27',
    completed: false,
    createdAt: '2023-10-20',
    assignedDoctor: 'Dr. Carlos Mendoza',
    autoGenerated: true,
  },
  {
    id: 'task-2',
    title: 'Solicitar renovación póliza mala praxis Dra. Ana Silva',
    description: 'Próxima a vencer el 30/10/2023. Notificar a secretaría.',
    category: 'Documentación',
    priority: 'Alta',
    dueDate: '2023-10-29',
    completed: false,
    createdAt: '2023-10-21',
    assignedDoctor: 'Dra. Ana Silva',
    autoGenerated: true,
  },
  {
    id: 'task-3',
    title: 'Imputar cobranza transferencia OSDE $1.450.000',
    description: 'Conciliar liquidaciones LIQ-24-090 y LIQ-24-085 con extracto bancario.',
    category: 'Tesorería',
    priority: 'Media',
    dueDate: '2023-10-28',
    completed: false,
    createdAt: '2023-10-22',
  },
  {
    id: 'task-4',
    title: 'Subir historia clínica para refacturación #88492',
    description: 'Paciente Rodríguez María Teresa - Consulta Especialista $12.500.',
    category: 'Débitos',
    priority: 'Alta',
    dueDate: '2023-10-26',
    completed: true,
    createdAt: '2023-10-18',
    assignedDoctor: 'Dr. Juan Pérez',
  },
  {
    id: 'task-5',
    title: 'Reclamar facturas morosas IOMA (+45 días)',
    description: 'Monto adeudado $2.150.000 correspondiente a período Enero 2024.',
    category: 'Obras Sociales',
    priority: 'Media',
    dueDate: '2023-10-30',
    completed: false,
    createdAt: '2023-10-23',
  },
  {
    id: 'task-6',
    title: 'Verificar credencial de Galeno en autorización AUT-2935',
    description: 'Paciente Lopez Carlos - Falta historia clínica adjunta.',
    category: 'General',
    priority: 'Baja',
    dueDate: '2023-10-31',
    completed: true,
    createdAt: '2023-10-19',
  },
];

export const INITIAL_AUTOMATION_LOGS: AutomationLog[] = [
  {
    id: 'log-1',
    timestamp: '2023-10-24T09:20:00',
    timeAgo: 'Hace 10 min',
    title: 'Emails enviados a 5 médicos',
    subtitle: 'Reporte mensual automático',
    type: 'email',
  },
  {
    id: 'log-2',
    timestamp: '2023-10-24T08:45:00',
    timeAgo: 'Hace 45 min',
    title: '15 autorizaciones validadas vía API',
    subtitle: 'Conexión exitosa con O.S.',
    type: 'api',
  },
  {
    id: 'log-3',
    timestamp: '2023-10-24T07:30:00',
    timeAgo: 'Hace 2 horas',
    title: 'Sincronización de padrón completada',
    subtitle: '2,450 registros actualizados',
    type: 'sync',
  },
  {
    id: 'log-4',
    timestamp: '2023-10-23T18:30:00',
    timeAgo: 'Ayer, 18:30',
    title: 'Fallo en descarga de liquidación',
    subtitle: 'Reintento programado en 1h',
    type: 'error',
  },
];
