export type TabKey =
  | 'inicio'
  | 'medicos'
  | 'bonos'
  | 'liquidaciones'
  | 'tesoreria'
  | 'debitos'
  | 'autorizaciones'
  | 'caja'
  | 'configuraciones'
  | 'tareas';

export interface Doctor {
  id: string;
  name: string;
  matricula: string;
  matriculaProvincial?: string;
  specialty: string;
  circuloMedico: string;
  avatar?: string;
  email: string;
  phone: string;
  docStatus: 'COMPLETO' | 'PENDIENTE' | 'REVISIÓN';
  placesOfCare: string[];
  conventions: string[];
  documentation: {
    matriculaNacionalFile?: string;
    matriculaNacionalUpdate?: string;
    matriculaNacionalStatus: 'Vigente' | 'No cargada' | 'Vencida';
    matriculaProvincialFile?: string;
    matriculaProvincialStatus: 'Vigente' | 'No cargada' | 'Pendiente';
    seguroMalaPraxisFile?: string;
    seguroMalaPraxisExpiry: string;
    seguroMalaPraxisStatus: 'Vigente' | 'Alerta' | 'Vencido';
  };
  automations: {
    emailAvisoVencimiento: boolean;
    envioResumenContador: boolean;
  };
}

export interface BonoItem {
  id: string;
  patientName: string;
  obraSocial: string;
  date: string;
  practiceCode: string;
  diagnosis: string;
  monto: number;
  copago: boolean;
  doctorId?: string;
  doctorName?: string;
}

export interface LiquidacionDoctor {
  id: string;
  doctorName: string;
  specialty: string;
  cantPracticas: number;
  monto: number;
  status: 'VERIFICADOS' | 'REVISIÓN' | 'PENDIENTE';
}

export interface Liquidacion {
  id: string;
  period: string; // e.g. "2023-10"
  obraSocial: string;
  modalidad: 'agrupada' | 'directa';
  practicasCount: number;
  montoTotal: number;
  doctorsCount: number;
  status: 'PROCESADA' | 'EN_REVISION' | 'PENDIENTE';
  doctorDetails: LiquidacionDoctor[];
}

export interface TreasuryEntry {
  id: string;
  obraSocial: string;
  amount: number;
  date: string;
  transferRef: string;
  createdAt: string;
}

export interface PendingFund {
  id: string;
  liqId: string;
  obraSocial: string;
  period: string;
  montoTotal: number;
  status: 'Pendiente' | 'Parcial' | 'Imputado';
  selected?: boolean;
}

export interface DebtorAlert {
  id: string;
  obraSocial: string;
  period: string;
  amount: number;
  overdueDays: number;
  contactEmail?: string;
}

export interface DebitItem {
  id: string;
  patientName: string;
  patientId: string;
  obraSocial: string;
  invoiceNumber: string;
  rejectionReason: 'Falta Historia Clínica' | 'Tope Excedido' | 'Código Inexistente' | 'Documentación Ilegible';
  practice: string;
  serviceDate: string;
  doctorName: string;
  doctorMatricula: string;
  amount: number;
  status: 'Pendiente' | 'Refacturado' | 'Aceptado Pérdida';
  attachedFile?: string;
  auditNotes: string;
}

export type KanbanColumn = 'pendientes' | 'tramite' | 'observadas' | 'aprobadas';

export interface AuthorizationItem {
  id: string;
  code: string;
  patientName: string;
  doctorName: string;
  obraSocial: string;
  timeAgo: string;
  status: KanbanColumn;
  isAutomation: boolean;
  observation?: string;
  progress?: number;
}

export interface CajaRecord {
  id: string;
  matricula: string;
  doctorName: string;
  specialty: string;
  grossBilling: number;
  retentionPercent: number; // e.g. 5
  retentionAmount: number;
  netPayable: number;
  status: 'Procesado' | 'Pendiente';
}

export interface ApiConnection {
  id: string;
  code: string;
  name: string;
  lastSync: string;
  status: 'Conectado' | 'Desconectado' | 'Sincronizando';
  endpointUrl?: string;
  apiKeyMasked?: string;
}

export interface MessagingRule {
  id: string;
  title: string;
  description: string;
  enabled: boolean;
  schedule: string;
  template: string;
}

export interface TaskItem {
  id: string;
  title: string;
  description?: string;
  category: 'Liquidaciones' | 'Débitos' | 'Documentación' | 'Tesorería' | 'General' | 'Obras Sociales';
  priority: 'Alta' | 'Media' | 'Baja';
  dueDate: string;
  completed: boolean;
  createdAt: string;
  assignedDoctor?: string;
  autoGenerated?: boolean;
}

export interface AutomationLog {
  id: string;
  timestamp: string;
  timeAgo: string;
  title: string;
  subtitle: string;
  type: 'email' | 'api' | 'sync' | 'error';
}
